# Generated by Django 4.2.23 on 2025-07-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerbanner',
            name='text_content',
            field=models.CharField(help_text='The text that will scroll on the banner.', max_length=600),
        ),
    ]
