# Generated by Django 4.2.23 on 2025-07-18 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at'], 'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Newsletter Subscriber', 'verbose_name_plural': 'Newsletter Subscribers'},
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='redeemable_price',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='items',
        ),
        migrations.AddField(
            model_name='coupon',
            name='applies_to_new_users_only',
            field=models.BooleanField(default=False, help_text='If checked, only users with no prior orders can use this coupon.'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_at',
            # FIX: Changed default=django.utils.timezone.now to default=django.utils.timezone.now()
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_orders_for_user',
            field=models.PositiveIntegerField(default=0, help_text='Minimum number of successful orders a user must have to use this coupon. (0 means no minimum).'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_total_items_in_cart',
            field=models.PositiveIntegerField(default=0, help_text='Minimum total quantity of items in the cart to use this coupon. (0 means no minimum).'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_unique_products_in_cart',
            field=models.PositiveIntegerField(default=0, help_text='Minimum number of different products in the cart to use this coupon. (0 means no minimum).'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of times this coupon can be used (0 for unlimited)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Number of times this coupon has been used'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='The unique code users will enter', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, help_text='Discount amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the coupon is currently active'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_purchase',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum total price required to use this coupon', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            # FIX: Changed default=1 to default=django.utils.timezone.now()
            field=models.DateTimeField(default=django.utils.timezone.now(), help_text='Date and time from which the coupon is valid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(help_text='Date and time until which the coupon is valid'),
        ),
    ]
