# Generated by Django 4.2.23 on 2025-07-18 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_offer_offerbanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-start_date'], 'verbose_name': 'Product Offer', 'verbose_name_plural': 'Product Offers'},
        ),
        migrations.AlterModelOptions(
            name='offerbanner',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Offer Banner', 'verbose_name_plural': 'Offer Banners'},
        ),
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='title',
        ),
        migrations.RemoveField(
            model_name='offerbanner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='offerbanner',
            name='link',
        ),
        migrations.RemoveField(
            model_name='offerbanner',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='offerbanner',
            name='title',
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed discount amount (e.g., 50.00 for $50 off).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (e.g., 10.00 for 10%).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.CharField(default='Untitled Offer', help_text="Name of the offer (e.g., 'Summer Sale', 'Flash Deal').", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Select products to apply this offer to.', related_name='offers', to='core.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='tag_text',
            field=models.CharField(default='SALE', help_text="Text to display as a tag on product cards (e.g., 'SALE', '20% OFF').", max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='offerbanner',
            name='bg_color',
            field=models.CharField(default='#FF0000', help_text='Hex color code for the background (e.g., #FF0000).', max_length=7),
        ),
        migrations.AddField(
            model_name='offerbanner',
            name='text_color',
            field=models.CharField(default='#FFFFFF', help_text='Hex color code for the text (e.g., #FFFFFF).', max_length=7),
        ),
        migrations.AddField(
            model_name='offerbanner',
            name='text_content',
            field=models.CharField(default='Default banner text', help_text='The text that will scroll on the banner.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerbanner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(help_text='Date and time when the offer expires.'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Overall status of the offer. Set to False to disable.'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the offer becomes active.'),
        ),
        migrations.AlterField(
            model_name='offerbanner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offerbanner',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Enable or disable this banner. Only one banner can be active at a time.'),
        ),
    ]
