# Generated by Django 4.2.23 on 2025-07-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_offer_options_alter_offerbanner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='background_color',
            field=models.CharField(default='#FF0000', help_text="Hex color code for tag background (e.g., #FF0000 or a named color like 'red')", max_length=7),
        ),
        migrations.AddField(
            model_name='offer',
            name='text_color',
            field=models.CharField(default='#FFFFFF', help_text="Hex color code for tag text (e.g., #FFFFFF or a named color like 'white')", max_length=7),
        ),
    ]
