# Generated by Django 4.2.23 on 2025-07-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_active_coupon_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
