# Generated by Django 4.2.23 on 2025-06-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_coupon_valid_from_coupon_valid_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='expiry_date',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateField(default='2099-12-31'),
            preserve_default=False,
        ),
    ]
