# Generated by Django 4.2.23 on 2025-07-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_is_reserved_cartitem_is_reserved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='custom_order_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
