# Generated by Django 4.2.23 on 2025-07-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_emailtemplate_newslettersubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercampaign',
            name='sent_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of emails actually sent'),
        ),
    ]
