# Generated by Django 4.2.23 on 2025-07-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_newslettercampaign_sent_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
