# Generated by Django 4.2.23 on 2025-06-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_country_userprofile_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='housename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
