# Generated by Django 4.2.23 on 2025-06-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_housename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
    ]
