# Generated by Django 4.2.23 on 2025-06-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_address_line_address_street_address_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='address_line',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='housename',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_default',
        ),
    ]
