# Generated by Django 4.2.23 on 2025-07-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_order_order_number_orderitem_is_cancelled_and_more'),
        ('core', '0022_returnrequest'),
    ]

    operations = [
    ]
